---
- name: ensure psycog2 package is installed (required by postgresql_* module from ansible)
  package:
    name: python-psycopg2
    state: present

- name: ensure /dumps directory exists
  file:
    path: /dumps
    state: directory

- name: ensure sql dumps are on the server
  copy:
    src: "{{ item.1.dump_sql }}"
    dest: "/dumps/{{ item.1.name }}.sql"
  with_subelements:
    - "{{ esme_database_postgres_environments }}"
    - databases
  when: item.1.dump_sql is defined

- name: ensure users exists on postgresql
  postgresql_user:
    name: "{{ item.user }}"
    password: "{{ item.password }}"
    role_attr_flags: CREATEDB
    login_host: 127.0.0.1
    login_password: "{{ esme_database_postgres_password }}"
  with_items: "{{ esme_database_postgres_environments }}"

- name: ensure databases has been loaded
  include_tasks: initialize_database.yml
  vars:
    db_name: "{{ item.1.name }}"
    db_user: "{{ item.0.user }}"
    db_state: "{{ item.1.state }}"
    db_restore: "{{ item.1.dump_sql is defined }}"
  with_subelements:
    - "{{ esme_database_postgres_environments }}"
    - databases
