---
# defaults file for esme_database.postgres
esme_database_postgres_steps:
  - initialize_postgres_container
  - initialize_databases

esme_database_postgres_mode: docker  # values : docker, local

esme_database_postgres_container_name: postgres
esme_database_postgres_port: 5432
esme_database_postgres_admin_user: postgres
esme_database_postgres_password: 1234

esme_database_postgres_environments:
  - user: user
    password: user
    databases:
      - name: sportsdb
        dump_sql: "files/dumps/sportsdb.sql"
        state: present
      - name: transtats
        dump_sql: "files/dumps/transtats.sql"
        state: present
      - name: pizza_shop
        dump_sql: "files/dumps/pizza_shop.sql"
        state: present
      - name: bio_icare_drone
        dump_sql: "files/dumps/bio_icare_drone.sql"
        state: present
      - name: bloon_project
        dump_sql: "files/dumps/bloon_project.sql"
        state: present
