---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: postgres
    image: postgres:11.5
    port_bindings:
      - 5432: 5432
    command: postgres
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ["ANSIBLE0010", "305", "503", "701", "703"]
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
