---

- name: ensure supervisord is installed
  apt:
    name: supervisor

- name: ensure /opt/esme_adminer directory exists
  file:
    path: /opt/esme_adminer
    state: directory

- name: ensure docker image definition is present on host
  copy:
    src: files/esme_adminer/Dockerfile
    dest: /opt/esme_adminer/Dockerfile
    force: true

- name: ensure docker image is build
  docker_image:
    path: /opt/esme_adminer
    name: esme_adminer

- name: ensure service configuration is setup
  template:
    src: templates/adminer.conf.j2
    dest: "/etc/supervisor/conf.d/{{ esme_database_adminer_container_name }}.conf"
    owner: root
    group: root
  register: esme_database_adminer_service_configuration

- name: ensure supervisord service configuration is reloaded
  command: supervisorctl reload
  when: esme_database_adminer_service_configuration.changed

- pause:
    seconds: 2

- name: ensure adminer service is started
  supervisorctl:
    name: "{{ esme_database_adminer_container_name }}"
    state: started
