---

- name: ensure apache package is installed
  apt: name=apache2 state=present

- name: ensure apache service is started
  service: name=apache2 state=started

- name: ensure packages required by adminer are installed
  apt: name={{ item }}
  with_items:
  - php7.0
  - php7.0-pgsql
  - libapache2-mod-php7.0
  notify:
  - ensure apache is restarting

- name: ensure adminer package is not setup
  apt:
    name: adminer
    state: absent

- name: ensure adminer directory exists
  file:
    path: /usr/share/adminer
    state: directory

- name: ensure latest version of adminer has been downloaded
  get_url:
    url: http://www.adminer.org/latest.php
    dest: /usr/share/adminer/adminer.php

- name: ensure adminer vhosts does not exists
  file:
    path: /etc/apache2/sites-enabled/020-adminer.conf
    state: absent

- name: ensure adminer vhosts exists on apache
  copy: src=files/adminer.conf dest=/etc/apache2/conf-enabled/020-adminer.conf
  notify:
  - ensure apache is restarting

- name: ensure php configuration are suffisant for file upload
  ini_file: dest=/etc/php5/apache2/php.ini section=PHP option={{ item.option }} value={{ item.value }}
  with_items:
  - {option: upload_max_filesize, value: 20M}
  - {option: post_max_size, value: 30M}
  - {option: memory_limit, value: 40M}
  notify:
  - ensure apache is restarting
