---

- name: Apache | Ensure package is installed
  apt: name=apache2 state=present

- name: Apache | Ensure service is started
  service: name=apache2 state=started

- name: Adminer | Ensure package is installed
  apt: name={{ item }}
  with_items:
  - php5
  - php5-pgsql
  - adminer
  notify:
  - Apache | Ensure service is reloaded

- name: Adminer | Ensure configuration linked with apache
  file: src=/etc/adminer/apache.conf dest=/etc/apache2/sites-enabled/020-adminer.conf state=link
  notify:
  - Apache | Ensure service is reloaded

- name: Adminer | Ensure php values is suffisant for upload
  ini_file: dest=/etc/php5/apache2/php.ini section=PHP option={{ item.option }} value={{ item.value }}
  with_items:
  - {option: upload_max_filesize, value: 20M}
  - {option: post_max_size, value: 30M}
  - {option: memory_limit, value: 40M}
  notify:
  - Apache | Ensure service is reloaded
