---
- hosts: infra
  become: yes
  become_method: sudo
  vars:

  tasks:

  - name: Apt | Ensure general packages are installed
    apt: name={{ item }} state=present
    with_items:
    - git
    - openjdk-8-jdk
    - maven

  - name: Apt | Ensure postgresql is installed
    apt: name={{ item }} state=present
    with_items:
    - postgresql-9.5
    - libpq-dev
    - python-psycopg2

  - name: Apt | Ensure postgis is installed
    apt: name={{ item }} state=present force=yes
    with_items:
    - postgresql-9.5-postgis-2.2
    - osm2pgsql
