---
- hosts: lab-postgres
  become: yes
  become_method: sudo
  vars:

  tasks:

    - name: Apt | Ensure general packages are installed
      apt: name={{ item }} state=present
      with_items:
      - git

  roles:
    - role: esme_database.postgres
      esme_database_postgres_environments: "{{ local_esme_database_postgres_environments }}"
    - role: esme_database.pgadmin
    - role: esme_database.adminer
