---
- hosts: lab-postgres
  become: yes
  become_method: sudo
  vars:


  roles:
    - role: docker
    - role: esme_database.postgres
      esme_database_postgres_environments: "{{ local_esme_database_postgres_environments }}"
    - role: esme_database.pgadmin
    - role: esme_database.adminer
    - role: esme_database.psqladmin
